import json

from paperforge.providers.base import ModelProvider, ModelRequest, ModelResponse

MOCK_MANUSCRIPT = """# Abstract
This evidence-safe demonstration manuscript was generated by the deterministic mock provider.

# Keywords
engineering; research workflow; evidence

# Introduction
The supplied research topic defines the scope of this demonstration.

# Related Work
No external sources were supplied for the offline demonstration.

# Methodology
Calibration, uncertainty, reproducibility parameters, and limitations must be documented from
authentic project evidence before submission.

# Results
No experimental result is asserted by the deterministic demonstration.

# Discussion
Interpretation is intentionally limited to the supplied evidence.

# Limitations
This mock output validates workflow behavior and does not represent completed research.

# Conclusion
The workflow completed without fabricating scientific claims.

# Declarations
The author must provide applicable declarations.

# References
No external references were supplied.
"""


class MockProvider(ModelProvider):
    """Deterministic provider for workflow tests and demonstrations."""

    def generate(self, request: ModelRequest) -> ModelResponse:
        replacement = MOCK_MANUSCRIPT if request.metadata.get("stage") == "initial_draft" else None
        return ModelResponse(
            content=json.dumps(
                {
                    "score": 1.0,
                    "findings": [],
                    "questions": [],
                    "patches": [],
                    "replacement_document": replacement,
                    "profile_update": None,
                    "notes": ["mock validation passed"],
                }
            ),
            model="deterministic-mock",
            provider="mock",
        )

    def healthcheck(self) -> tuple[bool, str]:
        return True, "Mock provider ready"
